### ISSUE TITLE
Why show stacktrace

### ISSUE THREAD

**Issue by awebdeveloper** [zumwald/better-vsts-npm-auth#10]
We need user consent before this script can run. Follow instructions in the browser window that just opened and then you can run this script again. If a browser does not open, paste https://app.vssps.visualstudio.com/oauth2/authorize?...../oauth-callback into your browser window and follow the instructions to grant permissions.
```
Error: missing refresh_token
  at Object.getUserAuthToken (.../better-vsts-npm-auth/lib/vsts-auth-client.js:48:27)
  at Function.authenticateRegistries (.../better-vsts-npm-auth/lib/registry-auth-reducer.js:148:29)
  at Promise.all.then.then.npmrcResults (.../better-vsts-npm-auth/index.js:64:57)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by zumwald** [comment]
makes sense. Published in 4.1.3
