### ISSUE TITLE
TypeError: Cannot read property 'stack' of undefined

### ISSUE THREAD

**Issue by rohithjidagam** [zumwald/better-vsts-npm-auth#12]
When running the better-vsts-npm-auth programaticaly by calling run method with no parameters, it is yielding the below issue. However, when passing {stack: true}, is making it run successfully.

ErrorLog Below:
-----------------

TypeError: Cannot read property 'stack' of undefined
    at Object.<anonymous> (D:\vsts-agent\_work\14\s\tools\glassjar\node_modules\better-vsts-npm-auth\dist\index.js:79:24)
    at next (native)
    at D:\vsts-agent\_work\14\s\tools\glassjar\node_modules\better-vsts-npm-auth\dist\index.js:7:71
    at __awaiter (D:\vsts-agent\_work\14\s\tools\glassjar\node_modules\better-vsts-npm-auth\dist\index.js:3:12)
    at Object.run (D:\vsts-agent\_work\14\s\tools\glassjar\node_modules\better-vsts-npm-auth\dist\index.js:44:12)

**Comment by zumwald** [comment]
Put together a trivial test and it does not reproduce. Please re-open with a gist if you have a repro.

```javascript
let { run } = require("better-vsts-npm-auth");

run();
```
