### ISSUE TITLE
exception in filterUniqueVstsRegistries: TypeError: url.indexOf is not a function

### ISSUE THREAD

**Issue by imWildCat** [zumwald/better-vsts-npm-auth#54]
```
$ better-vsts-npm-auth
config from /Users/[username]/.npmrc
config from /Users/[username]/Developer/workspace/myproj/.npmrc
exception in filterUniqueVstsRegistries: TypeError: url.indexOf is not a function
    at Object.isVstsFeedUrl (/Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/vsts-auth-client.js:28:15)
    at /Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:21:54
    at Array.filter (<anonymous>)
    at filterUniqueVstsRegistries (/Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:18:23)
    at Object.<anonymous> (/Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:73:40)
    at Generator.next (<anonymous>)
    at /Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:3:12)
    at Object.authenticateRegistries (/Users/[username]/.nvm/versions/node/v14.19.3/lib/node_modules/better-vsts-npm-auth/dist/lib/registry-auth-reducer.js:72:12)
```

**Comment by zumwald** [comment]
what's the content of `/Users/[username]/.npmrc` and `/Users/[username]/Developer/workspace/myproj/.npmrc` when you encounter this?

**Comment by imWildCat** [comment]
Sorry for the late reply. Here's the sample: https://gist.github.com/imWildCat/979d264e9e9cdeb4068505622a806d9d
